# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Keyvault-connection'
    KeyVaultName: 'armdevopskeyvault'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Production - DevOps2Portal'
    subscriptionId: '965d253f-2dc6-4cdf-8220-68e5a80f0c84'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rgARM'
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/shankatna/ARM/main/mainVM.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/shankatna/ARM/main/setVMValues.json'
    overrideParameters: '-adminPassword $(adminuseridpassword)'
    deploymentMode: 'Incremental'